# Generated by Django 5.1.3 on 2025-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='game_images/')),
                ('background', models.ImageField(upload_to='game_images/')),
                ('about', models.TextField()),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('age_rating', models.CharField(max_length=50)),
                ('official_website', models.URLField()),
                ('genres', models.ManyToManyField(to='pcloud.genre')),
            ],
        ),
    ]
