# Generated by Django 5.1.3 on 2025-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
